# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

before_install:
  - export TZ=US/Central
