# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; fi


r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
