# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: devel
      os: osx

sudo: required

before_install: -|
  curl -LO http://r.research.att.com/libs/clang-4.0.0-darwin15.6-Release.tar.gz
  sudo tar fvxz clang-4.0.0-darwin15.6-Release.tar.gz -C /

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
